# Prometheus configuration for Off the Grid monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'off-the-grid'
    env: 'production'

# Rule files
rule_files:
  - "alert_rules.yml"

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # cAdvisor - container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 15s

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 15s

  # FastAPI application metrics
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Next.js application metrics
  - job_name: 'nextjs-app'
    static_configs:
      - targets: ['host.docker.internal:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics
    scrape_timeout: 10s

  # BlackBox exporter for endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://host.docker.internal:8000/health
        - http://host.docker.internal:3000/api/health
        - http://host.docker.internal:8080  # pgAdmin
        - http://host.docker.internal:8081  # Redis Commander
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # BlackBox exporter for TCP monitoring
  - job_name: 'blackbox-tcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - host.docker.internal:5432  # PostgreSQL
        - host.docker.internal:6379  # Redis
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  # Docker daemon metrics
  - job_name: 'docker-daemon'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 15s

  # Custom application metrics from CLI tool
  - job_name: 'off-the-grid-cli'
    static_configs:
      - targets: ['host.docker.internal:9091']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

# Remote write for long-term storage (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.example.com/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 50GB